name: virallc
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blast
  - mafft
  - python
  - networkx
  - nextclade
  - biopython
  - seqtk
  - seqkit
  - pip
  - pip:
    - build
    - gitdir
    - virallc
